### ISSUE TITLE
[CS] 📚 Hash Table

### ISSUE THREAD

**Issue by eunjjungg** [jiwon2724/TIL#10]
## 질문
1. 해시함수는 해시충돌이 절대 일어나지 않는 함수이다. (O, X)
2. hash table 중 Direct-address table이란?

**Comment by jiwon2724** [comment]
1. X
2. 키 값을 주소로 사용하는 테이블임. 즉, 배열을 사용하여 레코드를 해당 키에 매핑하는 기능이 있는 데이터 구조
