### ISSUE TITLE
[CS] 📚 LCA

### ISSUE THREAD

**Issue by eunjjungg** [jiwon2724/TIL#13]
## 질문
1. 아래 사진에서 6, 7의 LCA를 구하는 과정을 간단한 순서도 or 글로 표현해주세요. 
![image](https://github.com/jiwon2724/TIL/assets/100047095/39449654-53a9-47d3-b896-ffd30c10abfb)

**Comment by jiwon2724** [comment]
1. 모든 노드에 대한 depth를 계산
2. 두 노드의 depth가 동일하도록 거슬로 올라감.
3. 그 이후 부모가 같아질 때까지 반복적으로 두 노드의 부모 방향으로 거슬러 올라감.
