### ISSUE TITLE
[CS] 📚 DP

### ISSUE THREAD

**Issue by eunjjungg** [jiwon2724/TIL#14]
## 질문
1. DP에서 제일 중요한 키워드가 뭐라고 생각하시나요? (복습을 위한 문제, 정답 따로 없음)

**Comment by jiwon2724** [comment]
1. 내 생각은 메모이제이션 같아. 한 가지 문제에 대해서, 단 한 번만 풀도록 만들어주는 알고리즘이기 때문에?

**Comment by eunjjungg** [comment]
👍 제가 생각하는 중요 키워드는 DP가 나오면 피하자 입니다. 하지만 두 번째로는 점화식을 찾아내는 과정이 제일 중요하다고 생각합니다. 잘못된 점화식을 세우는 순간 모든 풀이가 쓸모 없어지기 때문.. (메모이제이션하고 비슷한 얘기긴 함)
