### ISSUE TITLE
[CS] 📚 Selection Sort

### ISSUE THREAD

**Issue by eunjjungg** [jiwon2724/TIL#2]
## 질문
1. Selection Sort는 자료 이동이 많이 일어나는 편일까요? 아니라면 그 이유는?

**Comment by jiwon2724** [comment]
버블 정렬과 마찬가지로 swap 연산이 많이 일어납니다

**Comment by eunjjungg** [comment]
버블 연산에 비해 swap이 많이 일어나지는 않습니다. 선택 정렬은 1회전 시 한 번의 swap만 일어납니다.
