### ISSUE TITLE
[CS] 📚 Quick Sort

### ISSUE THREAD

**Issue by eunjjungg** [jiwon2724/TIL#4]
## 질문
1. 퀵 소트에서 피봇이 정해졌을 때 이 값을 기준으로 작은 값과 큰 값을 분리하는 로직에 대해 간단하게 설명해주세요.
2. 불안정 정렬인가요 아니면 안정 정렬인가요? 그리고 그 이유는?

**Comment by jiwon2724** [comment]
1. 피벗 기준으로 앞에는 피벗보다 값이 작은 원소, 뒤는 큰 원소로 나눔. 왼쪽 끝과 오른쪽 끝에서 움직이면서 서로 만날 때 새로운 피벗을 정함 -> 재귀

2. 불안정 정렬임. 피벗 값에 따라서 기존 위치가 지켜지지 않을 수도 있음.

**Comment by eunjjungg** [comment]
2번도 맞기는 한데 조금 보충 설명을 하자면 pivot과 같은 값이 left, right에 모두 걸려있을 때 left, right가 swap이 일어나잖아요~ 요런 케이스 때문에 불안정 정렬이라고 생각하구 전 문제를 내긴 했어요! 근데 어쨌든 답안도 같은 말씀을 하신 거 같네요~
