### ISSUE TITLE
[CS] 📚 Radix Sort

### ISSUE THREAD

**Issue by eunjjungg** [jiwon2724/TIL#7]
## 질문
1. 배열의 각 원소들의 자릿수가 모두 3자리일 경우 Radix Sort에서 LSD, MSD 둘 중 어느 방식을 채택하는 것이 맞나요?

**Comment by jiwon2724** [comment]
MSD방식 채택. 
문자열이나 고정 길이 정수 표현 정렬에 적합합니다.

**Comment by eunjjungg** [comment]
문제 출제 오류 ^0^;;
