### ISSUE TITLE
[CS] 📚 Counting Sort

### ISSUE THREAD

**Issue by eunjjungg** [jiwon2724/TIL#8]
## 질문
1. counting sort를 사용할만한 케이스를 하나 예시로 들어주세요.
2. 데이터의 값이 음수일 경우에 counting sort를 사용하지 못하는 이유?

**Comment by jiwon2724** [comment]
1. 1  ~ 10만 포함하고 있는 크기가 100인 배열에 해당 원소의 개수 출력 -> 1 ~ 10의 개수
2. 인덱스 제한
