### ISSUE TITLE
[CS] 📚 Binary Search

### ISSUE THREAD

**Issue by eunjjungg** [jiwon2724/TIL#9]
## 질문
1. 탐색을 진행하다 보면 left 값이 right 값보다 `A`해질 때 탐색을 멈춥니다. 이 `A`가 무엇인지와 왜 위와 같은 조건일 때 탐색을 그만두는지 간략하게 설명해주세요.

**Comment by jiwon2724** [comment]
1. `<=` 배열의 마지막 인덱스보다 같거나 커진 경우. 즉 찾아야 하는 값이 배열 범위 내에 없을 때 탐색을 종료함.
